--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/3/2024 5:10:21 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.catagory(CatagoryId, CatagoryName) VALUES
('db46a5eb-e794-11ee-acd2-7f3381ec1cc9', 'Unisex');
INSERT INTO dbferfurm.catagory(CatagoryId, CatagoryName) VALUES
('e1a6da57-e794-11ee-acd2-7f3381ec1cc9', 'Nam');
INSERT INTO dbferfurm.catagory(CatagoryId, CatagoryName) VALUES
('e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', 'Nữ');