--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/3/2024 5:10:21 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.manufactorer(ManufactorerId, Name) VALUES
('5f5bcd29-e832-11ee-acd2-7f3381ec1cc9', 'GUCCI');
INSERT INTO dbferfurm.manufactorer(ManufactorerId, Name) VALUES
('74314c47-e832-11ee-acd2-7f3381ec1cc9', 'VALENTINO');
INSERT INTO dbferfurm.manufactorer(ManufactorerId, Name) VALUES
('7e58fa07-e832-11ee-acd2-7f3381ec1cc9', 'NARCISO RODRIGUEZ');
INSERT INTO dbferfurm.manufactorer(ManufactorerId, Name) VALUES
('8d17488a-e832-11ee-acd2-7f3381ec1cc9', 'BURBERRY');
INSERT INTO dbferfurm.manufactorer(ManufactorerId, Name) VALUES
('94eccda6-e832-11ee-acd2-7f3381ec1cc9', 'VERSACE');
INSERT INTO dbferfurm.manufactorer(ManufactorerId, Name) VALUES
('9d33fd40-e832-11ee-acd2-7f3381ec1cc9', 'JO MALONE');