--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25/3/2024 10:28:55 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('000d0990-e833-11ee-acd2-7f3381ec1cc9', 'Dior Sauvage Eau de Toilette', 'https://i.postimg.cc/MThkBnjF/a1.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e1a6da57-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('00502f67-e833-11ee-acd2-7f3381ec1cc9', 'Dior Sauvage Eau de Parfum', 'https://i.postimg.cc/Bn8VTSJW/a2.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('009f7e26-e833-11ee-acd2-7f3381ec1cc9', 'Versace Pour Homme', 'https://i.postimg.cc/rp9FSXGk/a6.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('011d3dbc-e833-11ee-acd2-7f3381ec1cc9', 'Giorgio Armani Acqua Di Gio Pour Homme', 'https://i.postimg.cc/Lsh2ZYsz/b3.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('017bd3aa-e833-11ee-acd2-7f3381ec1cc9', 'Montblanc Explorer', 'https://i.postimg.cc/28fkXSHD/b2.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '74314c47-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('01de991c-e833-11ee-acd2-7f3381ec1cc9', 'Dolce & Gabbana The One Eau de Parfum for Men', 'https://i.postimg.cc/15cmx1TN/b4.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e1a6da57-e794-11ee-acd2-7f3381ec1cc9', '74314c47-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('022d4ecd-e833-11ee-acd2-7f3381ec1cc9', 'Versace Eros For Men', 'https://i.postimg.cc/vBH8hqX6/a8.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '74314c47-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('8256cca7-e795-11ee-acd2-7f3381ec1cc9', 'Seria', 'https://i.postimg.cc/Xvh3KjZt/a9.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('da6f64a7-e832-11ee-acd2-7f3381ec1cc9', 'Armaf Club de Nuit Intense Man', 'https://i.postimg.cc/nzB8vvfQ/b8.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('e6f25a0f-e832-11ee-acd2-7f3381ec1cc9', 'Versace Eros For Men', 'https://i.postimg.cc/tgb4ZCxk/a7.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fb55ccd4-e832-11ee-acd2-7f3381ec1cc9', 'Calvin Klein CK One', 'https://i.postimg.cc/g2zYmBFt/b6.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fc6e81e9-e832-11ee-acd2-7f3381ec1cc9', 'Afnan Supremacy Silver', 'b3.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fcfac61a-e832-11ee-acd2-7f3381ec1cc9', 'Calvin Klein CK Be', 'https://i.postimg.cc/HxymBqXn/b7.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fd62acc8-e832-11ee-acd2-7f3381ec1cc9', 'Chanel Bleu De Chanel Eau de Parfum', 'https://i.postimg.cc/15cmx1TN/b4.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fdc537c7-e832-11ee-acd2-7f3381ec1cc9', 'Versace Eros For Men Mini Size', 'https://i.postimg.cc/rp9FSXGk/a6.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fe232d83-e832-11ee-acd2-7f3381ec1cc9', 'Narciso Rodriguez For Him Bleu Noir Eau de Parfum', 'https://i.postimg.cc/J7X7qk5x/b1.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fe70dbd2-e832-11ee-acd2-7f3381ec1cc9', 'Yves Saint Laurent La Nuit De L''Homme', 'https://i.postimg.cc/jq32gbpq/a4.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fec25f4e-e832-11ee-acd2-7f3381ec1cc9', 'Versace Pour Homme Dylan Blue', 'https://i.postimg.cc/52Lt2F6j/a5.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '8d17488a-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('ff22a00b-e832-11ee-acd2-7f3381ec1cc9', 'Yves Saint Laurent Y Eau de Parfum', 'https://i.postimg.cc/CxY3bZcR/a3.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '8d17488a-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('ff6ab778-e832-11ee-acd2-7f3381ec1cc9', 'Calvin Klein CK One Travel Size', 'https://i.postimg.cc/52sf0qf4/b5.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '94eccda6-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('ffb9c0db-e832-11ee-acd2-7f3381ec1cc9', 'Nautica Voyage', 'https://i.postimg.cc/Xvh3KjZt/a9.webp', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '9d33fd40-e832-11ee-acd2-7f3381ec1cc9');