--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/3/2024 5:10:21 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('000d0990-e833-11ee-acd2-7f3381ec1cc9', 'Dior Sauvage Eau de Toilette', 'a1', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e1a6da57-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('00502f67-e833-11ee-acd2-7f3381ec1cc9', 'Dior Sauvage Eau de Parfum', 'a2', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('009f7e26-e833-11ee-acd2-7f3381ec1cc9', 'Versace Pour Homme', 'a3', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('011d3dbc-e833-11ee-acd2-7f3381ec1cc9', 'Giorgio Armani Acqua Di Gio Pour Homme', 'a4', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('017bd3aa-e833-11ee-acd2-7f3381ec1cc9', 'Montblanc Explorer', 'a5', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '74314c47-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('01de991c-e833-11ee-acd2-7f3381ec1cc9', 'Dolce & Gabbana The One Eau de Parfum for Men', 'a6', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e1a6da57-e794-11ee-acd2-7f3381ec1cc9', '74314c47-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('022d4ecd-e833-11ee-acd2-7f3381ec1cc9', 'Versace Eros For Men', 'a7', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '74314c47-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('8256cca7-e795-11ee-acd2-7f3381ec1cc9', 'Seria', 'a8', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'e6fff2b7-e794-11ee-acd2-7f3381ec1cc9', '5f5bcd29-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('da6f64a7-e832-11ee-acd2-7f3381ec1cc9', 'Armaf Club de Nuit Intense Man', 'a9', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('e6f25a0f-e832-11ee-acd2-7f3381ec1cc9', 'Versace Eros For Men', 'b1', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fb55ccd4-e832-11ee-acd2-7f3381ec1cc9', 'Calvin Klein CK One', 'b2', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fc6e81e9-e832-11ee-acd2-7f3381ec1cc9', 'Afnan Supremacy Silver', 'b3', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fcfac61a-e832-11ee-acd2-7f3381ec1cc9', 'Calvin Klein CK Be', 'b4', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fd62acc8-e832-11ee-acd2-7f3381ec1cc9', 'Chanel Bleu De Chanel Eau de Parfum', 'b5', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fdc537c7-e832-11ee-acd2-7f3381ec1cc9', 'Versace Eros For Men Mini Size', 'b6', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fe232d83-e832-11ee-acd2-7f3381ec1cc9', 'Narciso Rodriguez For Him Bleu Noir Eau de Parfum', 'b7', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fe70dbd2-e832-11ee-acd2-7f3381ec1cc9', 'Yves Saint Laurent La Nuit De L''Homme', 'b8', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '7e58fa07-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('fec25f4e-e832-11ee-acd2-7f3381ec1cc9', 'Versace Pour Homme Dylan Blue', 'b9', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '8d17488a-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('ff22a00b-e832-11ee-acd2-7f3381ec1cc9', 'Yves Saint Laurent Y Eau de Parfum', 'c1', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '8d17488a-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('ff6ab778-e832-11ee-acd2-7f3381ec1cc9', 'Calvin Klein CK One Travel Size', 'c2', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '94eccda6-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.product(ProductId, ProductName, Image, Quantity, Description, Price, CatagoryId, ManufactorerId) VALUES
('ffb9c0db-e832-11ee-acd2-7f3381ec1cc9', 'Nautica Voyage', 'c3', 20, 'Sự tinh tế trong mùi hương', 10000.00, 'db46a5eb-e794-11ee-acd2-7f3381ec1cc9', '9d33fd40-e832-11ee-acd2-7f3381ec1cc9');