--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/3/2024 5:10:21 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.user(UserId, Name, Address, PhoneNumber, Email, Role, Password) VALUES
('75cb55ed-e834-11ee-acd2-7f3381ec1cc9', '', '', '', 'hoang@gmail.com', 0, 'hoang12345');
INSERT INTO dbferfurm.user(UserId, Name, Address, PhoneNumber, Email, Role, Password) VALUES
('7d309a32-e834-11ee-acd2-7f3381ec1cc9', '', '', '', 'hong@gmail.com', 0, 'hong0111');
INSERT INTO dbferfurm.user(UserId, Name, Address, PhoneNumber, Email, Role, Password) VALUES
('7d78a959-e834-11ee-acd2-7f3381ec1cc9', '', '', '', 'anhdt@gmail.com', 0, '12345');
INSERT INTO dbferfurm.user(UserId, Name, Address, PhoneNumber, Email, Role, Password) VALUES
('7df06904-e834-11ee-acd2-7f3381ec1cc9', '', '', '', 'hoang@gmail.com', 0, 'hoang12345');