--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/5/2024 11:27:06 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.cart(CartId, ProductId, Quantity, Price, Image, UserId, ProductName) VALUES
('ad10a1bf-2d35-4086-8c22-e546086f0d68', '009f7e26-e833-11ee-acd2-7f3381ec1cc9', 1, 399000.00, 'https://i.postimg.cc/rp9FSXGk/a6.webp', '0c9e4f8d-4421-4ed0-aeb1-b90252b13754', 'Versace Pour Homme');
INSERT INTO dbferfurm.cart(CartId, ProductId, Quantity, Price, Image, UserId, ProductName) VALUES
('e7cf413e-d8f2-49c8-ad0d-1821ff3c279d', 'da6f64a7-e832-11ee-acd2-7f3381ec1cc9', 1, 799000.00, 'https://i.postimg.cc/nzB8vvfQ/b8.webp', '0c9e4f8d-4421-4ed0-aeb1-b90252b13754', 'Armaf Club de Nuit Intense Man');