--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/5/2024 11:27:06 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('0d2dc200-0170-4dd3-b50f-128341e9a156', 'Mình đã mua sản phẩm và rất hài lòng', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:22:22', '017bd3aa-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('0dd14f05-723f-42ee-96c4-07453b432ec3', 'sản phẩm này còn không shop', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:31:06', '000d0990-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('19074a2f-9781-46a6-96ce-d2b7de5a3967', 'Sản phẩm rất tốt', 1, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 13:47:39', '022d4ecd-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('1a5925f8-14f6-43dd-b0ac-02424dfdbae8', 'sản phẩm rất tốt', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:20:14', '000d0990-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('1bc4e193-a550-4107-a27d-9212aecfa8d0', 'Đã nhận hàng và rất hài lòng', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:07:59', 'e6f25a0f-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('22b241e1-442e-45c1-a933-bca5502daa80', 'Sản phẩm này còn không shop', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:27:44', '01de991c-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('36c21bde-b81e-472b-85b8-ba84f2211887', 'đánh giá 5 sao', 5, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 16:20:23', '022d4ecd-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('41fddd33-9427-40a7-b902-195e694f6cb8', 'đánh giá 4 sao', 4, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 16:20:38', '022d4ecd-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('4d433335-97a8-4654-8c2a-b856c70a0160', 'sản phẩm này còn không shop', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:38:12', '000d0990-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('62b01941-8210-4716-b756-cd4207190b0a', 'sản phẩm này mùi rất thơm', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 14:53:13', '009f7e26-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('82b02b32-4556-4919-aa6f-47430547dec2', 'Đã dùng thử và hơi thất vọng', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:39:15', '8256cca7-e795-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('86f98e77-ae20-4024-b23f-4a5671d18c85', 'đánh giá 2 sao', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:42:07', '8256cca7-e795-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('88825d29-41df-4c38-96df-78d40fcd3345', 'đánh giá 3 sao', 3, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:59:20', '8256cca7-e795-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('893cf5d0-aceb-4ef6-96f6-52030cbb996b', '', 4, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:57:57', '8256cca7-e795-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('8d0a3e47-d201-4c6b-9c80-c72912033f31', 'Mùi nước hoa này không dễ chịu như quảng cáo', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:10:01', 'fb55ccd4-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('c84b7e69-aa83-4a10-828a-e5c417c00036', 'sản phẩm này rất tốt', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '0001-01-01 00:00:00', 'da6f64a7-e832-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('d989fcc3-340a-454e-9340-220d72bf2868', 'đánh giá 1 sao', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:42:00', '8256cca7-e795-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('dafdd849-da99-490e-b886-49f6600e67b1', 'sản phẩm này còn không shop', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:29:45', '011d3dbc-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('ed4db8da-0b3c-41aa-a22c-7d84a4f45c4b', 'sản phẩm rất tốt', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:18:01', '000d0990-e833-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('eef460f1-b6a7-425c-8ef6-8b7b5fc6584f', 'đánh giá 1 sao', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 15:41:06', '8256cca7-e795-11ee-acd2-7f3381ec1cc9');
INSERT INTO dbferfurm.comment(CommentId, CommentContent, Rating, UserId, PostDate, ProductId) VALUES
('fc0647ac-5b51-4983-b9f0-c2d9b2171f11', 'sản phẩm rất tốt', 0, 'd3db6909-9b59-4508-9a58-7930d13ba1fc', '2024-05-01 14:53:13', '009f7e26-e833-11ee-acd2-7f3381ec1cc9');