--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/5/2024 11:27:06 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('08bda8e8-04ae-11ef-b0f5-8b6761b25bae', 'fd62acc8-e832-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('1cac9c13-008f-11ef-ad4d-80399b5cfee6', '000d0990-e833-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('78a89f78-008f-11ef-ad4d-80399b5cfee6', '00502f67-e833-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('b7d1db68-04ad-11ef-b0f5-8b6761b25bae', '009f7e26-e833-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('d067304a-04ad-11ef-b0f5-8b6761b25bae', '017bd3aa-e833-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('dfb7e69d-04ad-11ef-b0f5-8b6761b25bae', '022d4ecd-e833-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('ec98fb07-04ad-11ef-b0f5-8b6761b25bae', 'e6f25a0f-e832-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');
INSERT INTO dbferfurm.discount(DiscountId, ProductId, DiscountPercent, StartDate, EndDate) VALUES
('fa6e570c-04ad-11ef-b0f5-8b6761b25bae', 'fb55ccd4-e832-11ee-acd2-7f3381ec1cc9', 0.20, '2024-04-20', '2024-05-31');