--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/5/2024 11:27:06 PM
-- Server version: 10.5.23
--

SET NAMES 'utf8';

INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('03b66a6f-a0ae-4677-89b8-aca745d35099', '022d4ecd-e833-11ee-acd2-7f3381ec1cc9', '3a090a79-1639-445f-8030-95400008d970', 1, 239200.00, 'https://i.postimg.cc/vBH8hqX6/a8.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('13afffaa-d18b-4ffa-8988-50a6e9fcde67', 'e6f25a0f-e832-11ee-acd2-7f3381ec1cc9', 'acb66417-0eac-4f73-9fb0-c9afa492174c', 1, 319200.00, 'https://i.postimg.cc/tgb4ZCxk/a7.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('1c238e69-b574-4331-b97c-5b9b648062a4', 'da6f64a7-e832-11ee-acd2-7f3381ec1cc9', '1a366209-18f9-4da1-b61b-88c55ecf015c', 1, 799000.00, 'https://i.postimg.cc/nzB8vvfQ/b8.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('1c946e48-0f86-41d7-b1c8-27c2d82bf676', 'da6f64a7-e832-11ee-acd2-7f3381ec1cc9', '0f40c691-a1f7-4dc0-83bf-3b141137faf2', 3, 799000.00, 'https://i.postimg.cc/nzB8vvfQ/b8.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('1e1b977f-b055-47f7-8d46-0719c95a0bb1', 'fcfac61a-e832-11ee-acd2-7f3381ec1cc9', '85d2c8ae-4473-446f-b52c-1631a1e91c6b', 19, 599000.00, 'https://i.postimg.cc/HxymBqXn/b7.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('24a0ad94-1485-4c5b-bafc-77fb6c142702', 'fb55ccd4-e832-11ee-acd2-7f3381ec1cc9', 'acb66417-0eac-4f73-9fb0-c9afa492174c', 1, 399200.00, 'https://i.postimg.cc/g2zYmBFt/b6.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('332ba931-c708-4c6c-9032-7c3a74bbd904', 'da6f64a7-e832-11ee-acd2-7f3381ec1cc9', 'f7a49576-aee4-492d-bb48-61a1d59d3395', 2, 799000.00, 'https://i.postimg.cc/nzB8vvfQ/b8.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('38c80950-e79e-43a8-98db-b8f31ad6695e', 'e6f25a0f-e832-11ee-acd2-7f3381ec1cc9', 'ad77da82-3cbf-4323-93d1-da4216453b64', 4, 399000.00, 'https://i.postimg.cc/tgb4ZCxk/a7.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('40f4d3da-6439-4629-aa53-532bed963239', '022d4ecd-e833-11ee-acd2-7f3381ec1cc9', '0f40c691-a1f7-4dc0-83bf-3b141137faf2', 3, 299000.00, 'https://i.postimg.cc/vBH8hqX6/a8.webp');
INSERT INTO dbferfurm.orderdetail(OrderDetailId, ProductId, OrderId, Quantity, Price, Image) VALUES
('435e6d62-e576-4927-813b-dc2a504212e2', 'ff6ab778-e832-11ee-acd2-7f3381ec1cc9', 'f7a49576-aee4-492d-bb48-61a1d59d3395', 2, 399000.00, 'https://i.postimg.cc/52sf0qf4/b5.webp');